services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=magic
    networks:
      - planner_network
    ports:
      - "5432:5432"
    
  server:
    build: ./server
    environment:
      - HOST=0.0.0.0
    depends_on:
      - db
    networks:
      - planner_network
    ports:
      - "3000:3000"

  proxy:
    build: ./nginx
    depends_on:
      - server
    networks:
      - planner_network
    ports:
      - "80:80"

networks:
  planner_network:
    driver: bridge
    